//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassSystemManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class order_meal_systemEntities : DbContext
    {
        public order_meal_systemEntities()
            : base("name=order_meal_systemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<t訂餐_口味總表> t訂餐_口味總表 { get; set; }
        public virtual DbSet<t訂餐_店家風味表> t訂餐_店家風味表 { get; set; }
        public virtual DbSet<t訂餐_店家資料表> t訂餐_店家資料表 { get; set; }
        public virtual DbSet<t訂餐_訂單詳細資訊表> t訂餐_訂單詳細資訊表 { get; set; }
        public virtual DbSet<t訂餐_訂單資訊表> t訂餐_訂單資訊表 { get; set; }
        public virtual DbSet<t訂餐_評論表> t訂餐_評論表 { get; set; }
        public virtual DbSet<t訂餐_學員口味表> t訂餐_學員口味表 { get; set; }
        public virtual DbSet<t訂餐_學員最愛商家表> t訂餐_學員最愛商家表 { get; set; }
        public virtual DbSet<t訂餐_餐點資訊表> t訂餐_餐點資訊表 { get; set; }
        public virtual DbSet<t訂餐_營業時間表> t訂餐_營業時間表 { get; set; }
        public virtual DbSet<t會員_學生> t會員_學生 { get; set; }
    }
}
