//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassSystemManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class t訂餐_評論表
    {
        public int 評論表ID { get; set; }
        public int 訂單ID { get; set; }
        public string 評論 { get; set; }
        public string 滿意度_星數_ { get; set; }
    
        public virtual t訂餐_訂單資訊表 t訂餐_訂單資訊表 { get; set; }
    }
}
