//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassSystemManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class t訂餐_店家資料表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t訂餐_店家資料表()
        {
            this.t訂餐_店家風味表 = new HashSet<t訂餐_店家風味表>();
            this.t訂餐_訂單詳細資訊表 = new HashSet<t訂餐_訂單詳細資訊表>();
            this.t訂餐_學員最愛商家表 = new HashSet<t訂餐_學員最愛商家表>();
            this.t訂餐_餐點資訊表 = new HashSet<t訂餐_餐點資訊表>();
            this.t訂餐_營業時間表 = new HashSet<t訂餐_營業時間表>();
        }
    
        public int 店家ID { get; set; }
        public string 店家名稱 { get; set; }
        public string 地址 { get; set; }
        public string 電話 { get; set; }
        public string 餐廳介紹 { get; set; }
        public string 餐廳照片 { get; set; }
        public string 電子信箱 { get; set; }
        public string 密碼 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t訂餐_店家風味表> t訂餐_店家風味表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t訂餐_訂單詳細資訊表> t訂餐_訂單詳細資訊表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t訂餐_學員最愛商家表> t訂餐_學員最愛商家表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t訂餐_餐點資訊表> t訂餐_餐點資訊表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t訂餐_營業時間表> t訂餐_營業時間表 { get; set; }
    }
}
