//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassSystemManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class t訂餐_訂單資訊表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t訂餐_訂單資訊表()
        {
            this.t訂餐_訂單詳細資訊表 = new HashSet<t訂餐_訂單詳細資訊表>();
            this.t訂餐_評論表 = new HashSet<t訂餐_評論表>();
        }
    
        public int 訂單ID { get; set; }
        public string 訂單狀態 { get; set; }
        public int 學員ID { get; set; }
        public string 訂單時間 { get; set; }
        public string 支付方式 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t訂餐_訂單詳細資訊表> t訂餐_訂單詳細資訊表 { get; set; }
        public virtual t會員_學生 t會員_學生 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t訂餐_評論表> t訂餐_評論表 { get; set; }
    }
}
