//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassSystemManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class t訂餐_訂單詳細資訊表
    {
        public int 訂單詳細表ID { get; set; }
        public int 訂單ID { get; set; }
        public int 店家ID { get; set; }
        public int 餐點ID { get; set; }
        public Nullable<int> 餐點數量 { get; set; }
        public Nullable<decimal> 金額小記 { get; set; }
    
        public virtual t訂餐_店家資料表 t訂餐_店家資料表 { get; set; }
        public virtual t訂餐_訂單資訊表 t訂餐_訂單資訊表 { get; set; }
        public virtual t訂餐_餐點資訊表 t訂餐_餐點資訊表 { get; set; }
    }
}
